# Generated by Django 3.1.12 on 2024-12-05 01:34

import cargos.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('cargos', djongo.models.fields.ArrayField(model_container=cargos.models.Cargo)),
            ],
        ),
    ]
