# Generated by Django 3.1.12 on 2024-12-05 04:25

import cargos.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=20)),
                ('id_curso', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('cargos', djongo.models.fields.ArrayField(default=list, model_container=cargos.models.Cargo)),
            ],
            options={
                'db_table': 'estudiantes_estudiante',
            },
        ),
    ]
